### ISSUE TITLE
[Bug]: Reloading minecraft makes the blacklists no longer work

### ISSUE THREAD

**Issue by lubcubsgaming** [Mrbysco/FlatterEntities#1]
### General Info

- [x] I am running a modpack
- [x] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I am using the latest version of the mod

### Forge version

0.14.6

### Mod version

1.04

### Java version

java

### Issue Description

When reloading the instance. Mobs that were originally blacklisted. Appear 2d again and they only way to fix them is to go make a change in the config and hit save.

**Comment by Mrbysco** [comment]
Could you provide the latest log? and a version of the config and the same config but after reloading the instance
